Caching Proxy
meliosu/operating-systems-2 pull request #2
Opened 2024-10-05 12:21 UTC by meliosu

2024-11-22 06:13 UTC, Silhouette22 requested changes

2024-11-22 06:13 UTC, Silhouette22 commented on 3/hashmap.c
> +    for (int idx = h % map->len; 1; idx = (idx + 1) % map->len) {
А если у тебя в мапе не осталось свободного места, ты будешь в этом цикле бесконечно крутиться?

2024-11-22 06:13 UTC, Silhouette22 commented on 3/hashmap.c
> +        } else if (!strcmp(entry->key, key)) {
Аналогично вставке. А если у тебя, вдруг, много коллизий, из-за чего много сущностей с одним хэшем? Ты будешь бесконечно в этом цикле крутиться?

Да банальный пример - что будет, если размер мапы равен 1?

2024-11-22 06:13 UTC, Silhouette22 commented on 3/http.c
> +    request->parser.data = request;
Эти 2 строчки не должны идти в обратном порядке?

2024-11-22 06:13 UTC, Silhouette22 commented on 3/proxy.c
> +        int err = http_request_parse(&request, request_buffer + rcvd, n);
Хмм, интересно, а либа как-то хранит контекст того, что уже успело распарситься?
Просто если у тебя пришли за раз, условно 10 байт, а нужные тебе данные начинаются с 8го байта по 15й байт, то их целиком не будет ни в первой пачке данных, ни во второй. Распарсит ли тогда?

2024-11-22 06:13 UTC, Silhouette22 commented on 3/log.h
> +#define LOG_LEVEL_OFF 0
Когда задаешь какой-то набор взаимозаменяемых значений, имеет смысл сделать enum. Для твоих целей тут прям как раз будет)

2024-11-22 06:13 UTC, Silhouette22 commented on 3/log.h
> +#define LOG(level, label, color, fmt, args...)                                 \
Лучше тогда уж сделать inline-функцию. Задавать такие конструкции макросами - довольно плохой тон. Хотя, разработчики на C этим и грешат)
Поведение будет такое же, как и у директив препроцессора, т.е. они встроятся на этапе компиляции, но в отличие от них реальные функции дадут тебе статическую типизацию. В твои LOG(...) можно запихнуть много чего, в том числе с несоответствием типов, что тебе положит всё

2024-11-22 06:13 UTC, Silhouette22 commented on 3/log.h
> +#define LOG_LEVEL_OFF 0
Директивы препроцессора всё же другой цели служат

2024-11-22 06:13 UTC, Silhouette22 commented on 3/main.c
> +#define panic(fmt, args...)                                                    \
Посмотри на функцию err(3)

2024-11-22 06:13 UTC, Silhouette22 commented on 3/main.c
> +            panic("error accepting connection: %s", strerror(errno));
Для сервера, которым пользуются много клиентов, будет плохой практикой "падать", если не получилось подключить нового клиента. А если там уже 15 клиентов качают данные? Ошибка подключения 16го убьет и других клиентов?

2024-11-22 06:13 UTC, Silhouette22 commented on 3/net.c
> +        service = "80";
Можно вместо этого напистать "http" (см. services(5)). Тогда читаемость будет лучше

2024-11-22 06:13 UTC, Silhouette22 commented on 3/proxy.c
> +        return -1;
А здесь уже не нужно делать `stream_destroy(cached);`?

И, к слову, вот вместо -1 или 0 можно как раз объявить соответствующие директивы препроцессора. Это тоже сильно улучшит читаемость кода. Пока что то, что значит "-1" можно только догадываться из контекста

2024-11-22 06:13 UTC, Silhouette22 commented on 3/proxy.c
> +    if (looked_up) {
А не кажется тебе странным сначала приконнектиться к серверу, полностью отправить ему весь свой запрос, а потом только проверить, что такое соединение уже есть? И оборвать соединение с сервером

2024-11-22 06:13 UTC, Silhouette22 commented on 3/proxy.c
> +        if (stream->buffer->cap == stream->len) {
А, разве, сама эта проверка не находится внутри критической секции?

2024-11-22 19:05 UTC, meliosu commented on 3/hashmap.c
> +    for (int idx = h % map->len; 1; idx = (idx + 1) % map->len) {
добавил расширение мапы при вставке

2024-11-22 19:07 UTC, meliosu commented on 3/hashmap.c
> +        } else if (!strcmp(entry->key, key)) {
при поиске теперь бесконечного цикла не будет, так как количество элементов меньше количества ячеек

2024-11-22 19:08 UTC, meliosu commented on 3/proxy.c
> +        int err = http_request_parse(&request, request_buffer + rcvd, n);
URL полностью не хранился, пофиксил и добавил тест на это

2024-11-22 19:09 UTC, meliosu commented on 3/log.h
> +#define LOG_LEVEL_OFF 0
сменил на enum

2024-11-22 19:13 UTC, meliosu commented on 3/log.h
> +#define LOG(level, label, color, fmt, args...)                                 \
поменял на функции
LSP показывает сигнатуру и проверяет формат:
![image](https://github.com/user-attachments/assets/17aeba5e-5f1f-4135-9a95-1f716dd07210)

2024-11-22 19:13 UTC, meliosu commented on 3/main.c
> +            panic("error accepting connection: %s", strerror(errno));
исправил

2024-11-22 19:14 UTC, meliosu commented on 3/net.c
> +        service = "80";
исправил

2024-11-22 19:14 UTC, meliosu commented on 3/proxy.c
> +        return -1;
поменял -1 и 0 на ERROR и SUCCESS

2024-11-22 19:15 UTC, meliosu commented on 3/proxy.c
> +    if (looked_up) {
вынес `lookup_or_insert` до подключения к серверу

2024-11-22 19:22 UTC, meliosu commented on 3/proxy.c
> +        if (stream->buffer->cap == stream->len) {
теперь все операции с `stream` под мьютексом

2024-12-06 10:18 UTC, Silhouette22 approved these changes

2024-12-06 19:13 UTC, merged